//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;

[assembly: NeutralResourcesLanguageAttribute("en-US" , UltimateResourceFallbackLocation.MainAssembly)]

[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("TestProject1")]